pipeline {
    agent any
    stages {
        stage ('vcs') {
            steps {
                git url: 'https://github.com/gopijammula/MySpringPetclinicClone.git',
                branch: 'main'
            }
        }
        stage ('docker image build&push') {
            steps{
                git url: 'https://github.com/gopijammula/Docker_images.git',branch:'main'
                sh 'docker image build -t gopispc0117:1.0 . -f Dockerfile.spcmultistage'
                sh 'docker image tag gopispc0117:1.0 gopijammula1234/gopispc0117:1.0'
                sh ' docker login -u "gopijammula1234" -p "7036359627" docker.io'
                sh 'docker image push gopijammula1234/gopispc0117:1.0'
            }
        }
        stage ('terraform') {
            steps{
                git url: 'https://github.com/gopijammula/Devops_Notes.git',branch: 'main'
                sh 'terraform -chdir=Terraform/Templates/aks-cluster init'
                sh 'terraform -chdir=Terraform/Templates/aks-cluster apply -auto-approve'
            }
        }
        stage ('k8s'){
            steps{
                git url: 'https://github.com/gopijammula/Devops_Notes.git',branch: 'main'
                sh 'az aks get-credentials --resource-group gopiterraformcluster --name gopi-aks1'
                sh 'kubectl apply -f k8s/manifests/spc-deploy.yml'
                sh 'kubectl get po'
            }
        }
    }
}