---
- name: install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: installing java 
      ansible.builtin.apt:
        name: "{{ java_package }}"
        state: present
      when:
        - ansible_facts['distribution'] == 'ubuntu'
    - name: installing java on centos
      ansible.builtin.yum:
        name: "{{ java_package }}"
        state: present
      when:
        - ansible_facts['distribution'] == 'Centos'    
