apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: spc-deploy
spec:  
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      service: spc
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata: 
      name: spc_pod
      labels: 
        service: spc
    spec: 
      containers: 
        - name: gopispc
          image: gopijammula1234/gopispc0117:1.0
          ports: 
            - containerPort: 8080
              protocol: TCP
          readinessProbe: 
            httpGet:
              path: /
              port: 8080
          livenessProbe: 
            tcpSocket: 
              port: 8080
---
apiVersion: v1 
kind: Service
metadata: 
    name: gopi-spc-lb
spec:
  type: LoadBalancer
  selector: 
    service: spc
  ports:
    - name: webport
      port: 35000
      targetPort: 8080